(function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function h(){h=function(){};g.Symbol||(g.Symbol=ba)}var ca=0;function ba(a){return"jscomp_symbol_"+(a||"")+ca++}
function k(){h();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return l(this)}});k=function(){}}function l(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function da(a){k();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}
function m(a){if(!(a instanceof Array)){k();var b=a[Symbol.iterator];a=b?b.call(a):l(a);for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function ea(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
var n=window.Element.prototype,q=n.matches||n.matchesSelector||n.webkitMatchesSelector||n.mozMatchesSelector||n.msMatchesSelector||n.oMatchesSelector;function r(a,b){if(a&&1==a.nodeType&&b){if("string"==typeof b||1==b.nodeType)return a==b||t(a,b);if("length"in b)for(var c=0,d;d=b[c];c++)if(a==d||t(a,d))return!0}return!1}function t(a,b){if("string"!=typeof b)return!1;if(q)return q.call(a,b);b=a.parentNode.querySelectorAll(b);for(var c=0,d;d=b[c];c++)if(d==a)return!0;return!1}
function fa(a){for(var b=[];a&&a.parentNode&&1==a.parentNode.nodeType;)a=a.parentNode,b.push(a);return b}
function u(a,b,c){function d(a){var d;if(f.composed&&"function"==typeof a.composedPath)for(var e=a.composedPath(),p=0,w;w=e[p];p++)1==w.nodeType&&r(w,b)&&(d=w);else a:{if((d=a.target)&&1==d.nodeType&&b)for(d=[d].concat(fa(d)),e=0;p=d[e];e++)if(r(p,b)){d=p;break a}d=void 0}d&&c.call(d,a,d)}var e=document,f={composed:!0,u:!0},f=void 0===f?{}:f;e.addEventListener(a,d,f.u);return{g:function(){e.removeEventListener(a,d,f.u)}}}
function ha(a){var b={};if(!a||1!=a.nodeType)return b;a=a.attributes;if(!a.length)return{};for(var c=0,d;d=a[c];c++)b[d.name]=d.value;return b}var ia=/:(80|443)$/,v=document.createElement("a"),x={};
function y(a){a=a&&"."!=a?a:location.href;if(x[a])return x[a];v.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return y(v.href);var b="80"==v.port||"443"==v.port?"":v.port,b="0"==b?"":b,c=v.host.replace(ia,"");return x[a]={hash:v.hash,host:c,hostname:v.hostname,href:v.href,origin:v.origin?v.origin:v.protocol+"//"+c,pathname:"/"==v.pathname.charAt(0)?v.pathname:"/"+v.pathname,port:b,protocol:v.protocol,search:v.search}}
function z(a,b,c,d,e){if("function"==typeof d){var f=c.get("buildHitTask");return{buildHitTask:function(c){c.set(a,null,!0);c.set(b,null,!0);d(c,e);f(c)}}}return A({},a,b)}function B(a,b){var c=ha(a),d={};Object.keys(c).forEach(function(a){if(!a.indexOf(b)&&a!=b+"on"){var e=c[a];"true"==e&&(e=!0);"false"==e&&(e=!1);a=ja(a.slice(b.length));d[a]=e}});return d}
function ka(a,b){var c;return function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];clearTimeout(c);c=setTimeout(function(){return a.apply(null,[].concat(m(e)))},b)}}function la(a){function b(){c||(c=!0,a())}var c=!1;setTimeout(b,2E3);return b}var A=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(var e=0;d=c[e];e++)for(var f in d)Object.prototype.hasOwnProperty.call(d,f)&&(a[f]=d[f]);return a};
function ja(a){return a.replace(/[\-\_]+(\w?)/g,function(a,c){return c.toUpperCase()})}function C(a){return"object"==typeof a&&null!==a}
function D(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b}var E={G:1,v:2,H:3,w:4,J:5,A:6,B:7,K:8,L:9,I:10},F=Object.keys(E).length;
function G(a,b){a.set("\x26_av","2.0.1");var c=a.get("\x26_au"),c=parseInt(c||"0",16).toString(2);if(c.length<F)for(var d=F-c.length;d;)c="0"+c,d--;b=F-b;c=c.substr(0,b)+1+c.substr(b+1);a.set("\x26_au",parseInt(c||"0",2).toString(16))}
function H(a,b){var c=this;G(a,E.v);if(window.addEventListener){this.a=A({events:["click"],fieldsObj:{},attributePrefix:"ga-"},b);this.f=a;this.c=this.c.bind(this);var d="["+this.a.attributePrefix+"on]";this.b={};this.a.events.forEach(function(a){c.b[a]=u(a,d,c.c)})}}H.prototype.c=function(a,b){var c=this.a.attributePrefix;a.type==b.getAttribute(c+"on")&&(a=B(b,c),c=A({},this.a.fieldsObj,a),this.f.send(a.hitType||"event",z({transport:"beacon"},c,this.f,this.a.hitFilter,b)))};
H.prototype.remove=function(){var a=this;Object.keys(this.b).forEach(function(b){a.b[b].g()})};D("eventTracker",H);var I={};function J(a,b){G(a,E.w);window.matchMedia&&(this.a=A({changeTemplate:this.changeTemplate,changeTimeout:1E3,fieldsObj:{}},b),C(this.a.definitions)&&(b=this.a.definitions,this.a.definitions=Array.isArray(b)?b:[b],this.b=a,this.c=[],ma(this)))}
function ma(a){a.a.definitions.forEach(function(b){if(b.name&&b.dimensionIndex){var c=K(b);a.b.set("dimension"+b.dimensionIndex,c);na(a,b)}})}function K(a){var b;a.items.forEach(function(a){L(a.media).matches&&(b=a)});return b?b.name:"(not set)"}
function na(a,b){b.items.forEach(function(c){c=L(c.media);var d=ka(function(){var c=K(b),d=a.b.get("dimension"+b.dimensionIndex);c!==d&&(a.b.set("dimension"+b.dimensionIndex,c),c={transport:"beacon",eventCategory:b.name,eventAction:"change",eventLabel:a.a.changeTemplate(d,c),nonInteraction:!0},a.b.send("event",z(c,a.a.fieldsObj,a.b,a.a.hitFilter)))},a.a.changeTimeout);c.addListener(d);a.c.push({F:c,D:d})})}J.prototype.remove=function(){for(var a=0,b;b=this.c[a];a++)b.F.removeListener(b.D)};
J.prototype.changeTemplate=function(a,b){return a+" \x3d\x3e "+b};D("mediaQueryTracker",J);function L(a){return I[a]||(I[a]=window.matchMedia(a))}function M(a,b){var c=this;G(a,E.A);window.addEventListener&&(this.a=A({events:["click"],linkSelector:"a, area",shouldTrackOutboundLink:this.shouldTrackOutboundLink,fieldsObj:{},attributePrefix:"ga-"},b),this.f=a,this.c=this.c.bind(this),this.b={},this.a.events.forEach(function(a){c.b[a]=u(a,c.a.linkSelector,c.c)}))}
M.prototype.c=function(a,b){if(this.a.shouldTrackOutboundLink(b,y)){var c=b.getAttribute("href")||b.getAttribute("xlink:href"),d=y(c),e={transport:"beacon",eventCategory:"Outbound Link",eventAction:a.type,eventLabel:d.href};navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which||window.addEventListener("click",function(a){a.defaultPrevented||(a.preventDefault(),e.hitCallback=la(function(){location.href=c}))});a=A({},this.a.fieldsObj,B(b,this.a.attributePrefix));
this.f.send("event",z(e,a,this.f,this.a.hitFilter,b))}};M.prototype.shouldTrackOutboundLink=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname!=location.hostname&&"http"==b.protocol.slice(0,4)};M.prototype.remove=function(){var a=this;Object.keys(this.b).forEach(function(b){a.b[b].g()})};D("outboundLinkTracker",M);var N=[];
function O(a,b){var c=this;this.context=a;this.s=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.a=[];this.b=[];this.h=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return c.b[c.b.length-1].apply(null,[].concat(m(b)))};this.c?a.set(b,this.h):a[b]=this.h}function P(a,b){b=a.a.indexOf(b);-1<b&&(a.a.splice(b,1),0<a.a.length?Q(a):a.g())}function Q(a){a.b=[];for(var b,c=0;b=a.a[c];c++){var d=a.b[c-1]||a.f.bind(a.context);a.b.push(b(d))}}
O.prototype.g=function(){var a=N.indexOf(this);-1<a&&(N.splice(a,1),this.c?this.context.set(this.s,this.f):this.context[this.s]=this.f)};function R(a,b){var c=N.filter(function(c){return c.context==a&&c.s==b})[0];c||(c=new O(a,b),N.push(c));return c}function S(){this.a={}}S.prototype.C=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];(this.a[a]=this.a[a]||[]).forEach(function(a){return a.apply(null,[].concat(m(c)))})};var T={},U=!1;
function V(a,b){this.a={};this.key=a;this.l=b||{}}ea(V,S);function oa(a,b,c){a=["autotrack",a,b].join(":");T[a]||(T[a]=new V(a,c),T[a].key=a,U||(window.addEventListener("storage",pa),U=!0));return T[a]}V.prototype.get=function(){var a=String(window.localStorage&&window.localStorage.getItem(this.key));return"string"!=typeof a?{}:W(a,this.l)};V.prototype.set=function(a){var b=this.get();a=A(b,a);window.localStorage&&window.localStorage.setItem(this.key,JSON.stringify(a))};
V.prototype.g=function(){delete T[this.key];Object.keys(T).length||(window.removeEventListener("storage",pa),U=!1)};function pa(a){var b=T[a.key];if(b){var c=W(a.oldValue,b.l);a=W(a.newValue,b.l);b.C("externalSet",a,c)}}function W(a,b){var c;try{c=JSON.parse(a)}catch(d){c={}}return A({},b,c)}var qa={};
function X(a,b,c){this.f=a;this.timeout=b||ra;this.timeZone=c;b=this.b=this.b.bind(this);c=R(a,"sendHitTask");c.a.push(b);Q(c);try{this.c=new Intl.DateTimeFormat("en-US",{timeZone:this.timeZone})}catch(d){}this.a=oa(a.get("trackingId"),"session",{hitTime:0,isExpired:!1})}X.prototype.isExpired=function(a){a=a?a:this.a.get();if(a.isExpired)return!0;var b=new Date,c=(a=a.hitTime)&&new Date(a);return a&&(b-c>6E4*this.timeout||this.c&&this.c.format(b)!=this.c.format(c))?!0:!1};
X.prototype.b=function(a){var b=this;return function(c){a(c);var d=b.a.get(),e=b.isExpired(d);c=c.get("sessionControl");d.hitTime=+new Date;if("start"==c||e)d.isExpired=!1;"end"==c&&(d.isExpired=!0);b.a.set(d)}};X.prototype.g=function(){var a=this.b;P(R(this.f,"sendHitTask"),a);this.a.g();delete qa[this.f.get("trackingId")]};var ra=30,Y=function sa(b){return b?(b^16*Math.random()>>b/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,sa)}();
function Z(a,b){G(a,E.B);if(window.addEventListener){this.a=A({sessionTimeout:ra,fieldsObj:{}},b);this.f=a;this.i=null;this.j=this.j.bind(this);this.b=this.b.bind(this);this.h=this.h.bind(this);this.m=this.m.bind(this);this.c=oa(a.get("trackingId"),"plugins/page-visibility-tracker");b=this.m;var c=this.c;(c.a.externalSet=c.a.externalSet||[]).push(b);this.o=new X(a,this.a.sessionTimeout,this.a.timeZone);b=this.j;a=R(a,"set");a.a.push(b);Q(a);document.addEventListener("visibilitychange",this.b);window.addEventListener("unload",
this.h);"visible"==document.visibilityState&&this.b()}}
Z.prototype.b=function(){var a=this.c.get();"visible"==this.i&&"hidden"==a.state&&a.pageId!=Y&&(a.state="visible",a.pageId=Y,this.c.set(a));var b={time:+new Date,state:document.visibilityState,pageId:Y};this.o.isExpired()?"hidden"==document.visibilityState?window.localStorage&&window.localStorage.removeItem(this.c.key):(this.f.send("pageview",z({transport:"beacon"},this.a.fieldsObj,this.f,this.a.hitFilter)),this.c.set(b)):(a.pageId==Y&&"visible"==a.state&&ta(this,a),this.c.set(b));this.i=document.visibilityState};
function ta(a,b,c){var d={transport:"beacon",nonInteraction:!0,eventCategory:"Page Visibility",eventAction:"track",eventLabel:"(not set)"};c&&(d.M=+new Date-c);var e=c,e=void 0===e?+new Date:e;c=!a.o.isExpired();b=b.time&&Math.round((e-b.time)/1E3);if(b=c&&0<b?b:0)d.eventValue=b,a.a.visibleMetricIndex&&(d["metric"+a.a.visibleMetricIndex]=b);a.f.send("event",z(d,a.a.fieldsObj,a.f,a.a.hitFilter))}
Z.prototype.j=function(a){var b=this;return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e={};e=C(d[0])?d[0]:(e[d[0]]=d[1],e);e.page&&e.page!==b.f.get("page")&&"visible"==b.i&&b.b();a.apply(null,[].concat(m(d)))}};Z.prototype.m=function(a,b){a.time!=b.time&&b.pageId==Y&&"visible"==b.state&&ta(this,b,a.time)};Z.prototype.h=function(){"hidden"!=this.i&&this.b()};
Z.prototype.remove=function(){this.o.g();var a=this.j;P(R(this.f,"set"),a);window.removeEventListener("unload",this.h);document.removeEventListener("visibilitychange",this.b)};D("pageVisibilityTracker",Z);})();
//# sourceMappingURL=autotrack.custom.js.map